### ISSUE TITLE
meteor application and sticky session

### ISSUE THREAD

**Issue by aboire** [coldbrewcloud/coldbrew-cli#28]
I have a question I just tested with a meteor application deployment and everything to walk properly it's a great job, but what should set up on ELB (ALB) sticky session for the websocket?

If yes can be put an option to add it directly in the configuration?

**Comment by d5** [comment]
coldbrew-cli does not have a configuration for that specifically, but, you can easily enable sticky sessions by configuring the Target Group using AWS console, SDK, or CLI tool. http://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-target-group-attributes.html
