### ISSUE TITLE
Update ECS agent version and version 1.4.1 

### ISSUE THREAD

**Issue by aboire** [coldbrewcloud/coldbrew-cli#34]
This is a great tool, just to let you know that ECS agent version has changed to version 1.13.1, and version 1.4.1 is not present in releases

**Comment by d5** [comment]
I will update the base image soon :) Thanks!

**Comment by d5** [comment]
I'm updating default AMI to install the latest ECS agent (1.13.1) right now. 

But note that this will *NOT* automatically update the existing ECS clusters, but, you can use AWS CLI command if you want to update the agent versions in your container instances manually:
```
aws ecs update-container-agent --cluster cluster_name --container-instance container_instance_id
```
See [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/agent-update-ecs-ami.html) for more info.
