### ISSUE TITLE
panic: interface conversion: io.Writer is *colorable.Writer, not *os.File

### ISSUE THREAD

**Issue by Jonesie** [coldbrewcloud/coldbrew-cli#42]
Every command I try gives me this error:

panic: interface conversion: io.Writer is *colorable.Writer, not *os.File

Running on windows 10.

**Comment by d5** [comment]
Can you possibly test if this PR #45  fixes this issue? @Jonesie

**Comment by pau-sullivan** [comment]
Did  you solve it? I'm getting this error too

**Comment by Jonesie** [comment]
Sorry, I didnt see this until now. Not using coldbrew - brewed my own cloudformations.

**Comment by ralc** [comment]
I am getting this issue.  Is this still being supported?

**Comment by harshal7harshal** [comment]
any command I run its giving same error what are we missing here in windows?


panic: interface conversion: io.Writer is *colorable.Writer, not *os.File

goroutine 1 [running]:
github.com/coldbrewcloud/coldbrew-cli/vendor/github.com/d5/cc.Enable()
        /home/travis/gopath/src/github.com/coldbrewcloud/coldbrew-cli/vendor/github.com/d5/cc/colors.go:52 +0x107
github.com/coldbrewcloud/coldbrew-cli/vendor/github.com/d5/cc.init.0()
        /home/travis/gopath/src/github.com/coldbrewcloud/coldbrew-cli/vendor/github.com/d5/cc/colors.go:249 +0xd4
github.com/coldbrewcloud/coldbrew-cli/vendor/github.com/d5/cc.init()
        <autogenerated>:1 +0x88
github.com/coldbrewcloud/coldbrew-cli/console.init()
        <autogenerated>:1 +0x4d
github.com/coldbrewcloud/coldbrew-cli/commands/clustercreate.init()
        <autogenerated>:1 +0x57
main.init()
        <autogenerated>:1 +0x52

**Comment by d5** [comment]
I merged a PR that's supposed to fix this. Let me know if the latest binary fix it or not. Btw, coldbrew-cli is not actively maintained at the moment. _(Business was shut down.)_ You should consider using other options, such as acs-cli.
